# Generated by Django 4.1.7 on 2023-04-23 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngoprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo_details',
            name='googleLocation',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
